### ISSUE TITLE
Missing driver for BSEC

### ISSUE THREAD

**Issue by danieasv** [mcallistertad/nrf_google_iot_core#4]
Noticed that I had to install the driver for BSEC from [Bosch](https://www.bosch-sensortec.com/media/boschsensortec/downloads/bsec/bsec_1-4-7-4_generic_release.zip 
) and place it in the `/nrf/ext/BSEC_1.4.7.4_Generic_Release` directory to get your code to work.

**Comment by mcallistertad** [comment]
Hi Daniel,

It's not included as a license agreement needs to be signed. I will update the readme.

https://www.bosch-sensortec.com/media/boschsensortec/downloads/bsec/2017-07-17_clickthrough_license_terms_environmentalib_sw_clean.pdf
